name: Convert MPD to M3U8

on:
  workflow_dispatch: # Memungkinkan workflow dijalankan manual dari GitHub UI

jobs:
  convert-mpd-to-m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Convert MPD to M3U8
      env:
        MPD_URL: "http://test.tipiku.biz.id/drm/dash/17875_stream.mpd?hdnts=exp=1737043717~acl=/drm/dash/17875*~id=164435459~hmac=a71d14fb04726114dded77400b7f2630ac132e6e215b27522275525cf382ab5b" # Ganti dengan URL MPD Anda
        CLEARKEY: "da9b3e7a19a1430b19047792fc6add67" # Key Anda
        OUTPUT_FILE: "output.m3u8"
      run: |
        echo "Starting MPD to M3U8 conversion..."

        ffmpeg -decryption_key $CLEARKEY \
               -i $MPD_URL \
               -c:v copy -c:a copy \
               -hls_time 4 -hls_playlist_type event \
               $OUTPUT_FILE

        echo "Conversion completed: $OUTPUT_FILE"

    - name: Upload M3U8 to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: converted-m3u8
        path: output.m3u8
