name: MPD to M3U8 Conversion

on:
  workflow_dispatch:
    inputs:
      mpd_url:
        description: "URL of the MPD file"
        required: true
        type: string
      decryption_key:
        description: "Decryption key for Widevine/ClearKey (optional)"
        required: false
        type: string

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget aria2
        
        # Download Shaka Packager
        wget -q https://github.com/shaka-project/shaka-packager/releases/download/v3.4.1/packager-linux-x64 -O packager
        chmod +x packager
        sudo mv packager /usr/local/bin/packager

    - name: Validate MPD File
      run: |
        wget "${{ github.event.inputs.mpd_url }}" -O master.mpd || exit 1
        echo "MPD file downloaded successfully."

    - name: Convert MPD to M3U8
      run: |
        if [ -n "${{ github.event.inputs.decryption_key }}" ]; then
          packager \
            input=${{ github.event.inputs.mpd_url }},stream=video,output=output_video.mp4 \
            --decryption_key=${{ github.event.inputs.decryption_key }} \
            --enable_widevine_decryption
        else
          packager \
            input=${{ github.event.inputs.mpd_url }},stream=video,output=output_video.mp4
        fi
      env:
        MPD_URL: ${{ github.event.inputs.mpd_url }}
        DECRYPTION_KEY: ${{ github.event.inputs.decryption_key }}

    - name: Upload Converted Files
      uses: actions/upload-artifact@v3
      with:
        name: converted-video
        path: output_video.mp4
