name: Convert MPD to M3U8

on:
  workflow_dispatch: # Memungkinkan workflow dijalankan manual dari GitHub UI

jobs:
  convert-mpd-to-m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Convert MPD to M3U8
      env:
        MPD_URL: "https://ottb.live.cf.ww.aiv-cdn.net/lhr-nitro/live/clients/dash/enc/wf8usag51e/out/v1/bd3b0c314fff4bb1ab4693358f3cd2d3/cenc.mpd"
        CLEARKEY: "63ac662dde310cfb4cc6f9b43b34196d" # Key Anda
        OUTPUT_FILE: "output.m3u8"
      run: |
        echo "Starting MPD to M3U8 conversion..."

        ffmpeg -decryption_key $CLEARKEY \
               -i $MPD_URL \
               -c:v copy -c:a copy \
               -hls_time 4 -hls_playlist_type event \
               $OUTPUT_FILE

        echo "Conversion completed: $OUTPUT_FILE"

    - name: Upload M3U8 to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: converted-m3u8
        path: output.m3u8
